import Head from "next/head";
import Script from "next/script";
import Image from "next/image";
import Link from "next/link";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <div className={styles.container}>
      <style jsx>
        {`
          h2 {
            font-size: 40px;
          }
          h3 {
            font-size: 30px;
          }
        `}
      </style>
      <Head>
        <title>Hunting Coder</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        {/* <script src="../public/sc.js"></script> */}
      </Head>
      {/* <Script src="/sc.js" strategy="lazyOnload"></Script> */}

      <main className={`${styles.main} ${inter.className}`}>
        <h1 className={styles.title}>Hunting Coder</h1>
        <div className={styles.imagewrap}>
          <Image
            className={styles.myImg}
            src="/unsplash.avif"
            alt=""
            width={237}
            height={158}
          ></Image>
        </div>
        <p className={styles.description}>
          A blog for hunting coders by a hunting coder
          {/* <p>
            Hunting Coders&nbsp;
            <code className={styles.code}>src/pages/index.js</code>
          </p> */}
          {/* <div>
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              A blog by coders
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                className={styles.vercelLogo}
                width={100}
                height={24}
                priority
              />
            </a>
          </div> */}
        </p>
        <div className="blogs">
          <h2>Latest Blogs</h2>
          <div className="blogItem">
            <h3>How to learn Javascript in 2022</h3>
            <p>Javascript language is used to design language for web</p>
          </div>
          <div className="blogItem">
            <h3>How to learn Javascript in 2022</h3>
            <p>Javascript language is used to design language for web</p>
          </div>
          <div className="blogItem">
            <h3>How to learn Javascript in 2022</h3>
            <p>Javascript language is used to design language for web</p>
          </div>
        </div>
        {/* <div className={styles.grid}>
            <a
              href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              className={styles.card}
              target="_blank"
              rel="noopener noreferrer"
            >
              <h2>
                Docs <span>-&gt;</span>
              </h2>
              <p>
                Find in-depth information about Next.js features and&nbsp;API.
              </p>
            </a>

            <a
              href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              className={styles.card}
              target="_blank"
              rel="noopener noreferrer"
            >
              <h2>
                Learn <span>-&gt;</span>
              </h2>
              <p>
                Learn about Next.js in an interactive course with&nbsp;quizzes!
              </p>
            </a>

            <a
              href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              className={styles.card}
              target="_blank"
              rel="noopener noreferrer"
            >
              <h2>
                Templates <span>-&gt;</span>
              </h2>
              <p>
                Discover and deploy boilerplate example Next.js&nbsp;projects.
              </p>
            </a>

            <a
              href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              className={styles.card}
              target="_blank"
              rel="noopener noreferrer"
            >
              <h2>
                Deploy <span>-&gt;</span>
              </h2>
              <p>
                Instantly deploy your Next.js site to a shareable URL
                with&nbsp;Vercel.
              </p>
            </a>
          </div> */}
      </main>
    </div>
  );
}
